# Generated by Django 5.2.1 on 2025-07-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('paypal', 'PayPal'), ('transferencia', 'Transferencia Bancaria'), ('criptomoneda', 'Criptomoneda')], max_length=50)),
                ('estado_pago', models.CharField(choices=[('completado', 'Completado'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], max_length=20)),
            ],
        ),
    ]
